### ISSUE TITLE
Extension fails to work for new rooms on beta.crunchyroll.com

### ISSUE THREAD

**Issue by JeromySt** [samuraiexx/roll_together#14]
Just wanting to report that the extension is not working as intended on beta.crunchyroll.com.  This is likely a temporary issue until they go live with it but I wanted to let you know.

The beta can join an in-progress room, just there is no button to create a room.

**Comment by samuraiexx** [comment]
Thank you for your feedback!

I just merged a commit that's supposed to fix that issue.
Can you update the extension to version 2.9.1 and confirm if the issue persists?

**Comment by JeromySt** [comment]
Hello.  I updated the extension and not it does not appear to load on either the normal site nor the beta site.

**Comment by hsnavarro** [comment]
Could you please provide the full url (both normal and beta) of the episode where you are trying to use the extension.

**Comment by JeromySt** [comment]
https://beta.crunchyroll.com/watch/GN7UDZXWX/Divide
and
https://www.crunchyroll.com/rwby/episode-1-divide-798820

In both cases clicking on the RT icon only displays the Roll Together extension menu, no ability to create a Room.  Previous to 2.9.1 the www.crunchyroll.com URI would properly show the Create a Room option.

**Comment by hsnavarro** [comment]
The extension is activated using a regex expression and both URLs that you sent passed when testing, so it shouldn't have any problem with showing the Create Room button properly. Both I and @samuraiexx have tried without success to reproduce this issue using Chrome for Windows x64. Are you using another browser? I would ask you to also try to reinstall the extension and reaccept the permission and see if works.

**Comment by JeromySt** [comment]
I'm using Microsoft Edge Chromium.  I'll try re-installing the extension and report back.

**Comment by JeromySt** [comment]
Ok... re-install found the extension working on www.crunchyroll.com:
![image](https://user-images.githubusercontent.com/12549141/112089113-40743680-8b4e-11eb-9795-fd03d7084076.png)

beta.crunchyroll.com:
![image](https://user-images.githubusercontent.com/12549141/112089255-83360e80-8b4e-11eb-9979-a043d8833a0d.png)

note that extension installation only mentions www.crunchyroll.com (not sure if that matters):
![image](https://user-images.githubusercontent.com/12549141/112089327-a791eb00-8b4e-11eb-950a-71deee1e23ff.png)

I think my previous issue with www.crunchyroll.com was with in-private/incognito session trying to test non-beta site before I figured out I could switch back and forth easily.  So it would seem the regex isn't yet properly loading the extension on the beta site for some reason.

**Comment by samuraiexx** [comment]
@JeromySt thank you very much, that was a really complete description.

I'll start testing it on Edge as well and try to understand why you had to reinstall it but nice to know that people also use this extension on Edge.

If you are interested in the bug:

> To make it easier to know when you can create a room, we do not show the "Create" option depending on your current URL and on the existence of an IFrame# with id #vilos-player.
> 
> My guess, now that allowing all Crunchyroll subdomains didn't work, is that on beta the IFrame Id is not vilos-player so instead of querying that, I changed to query the IFrame source that's for sure still static.crunchyroll - thanks to your comment that ensured that it was still working, even though no room was being created.
 
I'll wait for @hsnavarro to take a look at my PR and if everything is fine I'll deploy and let you know here when the new version is released.

Again, thank you =]

**Comment by JeromySt** [comment]
I have exported the source for an example beta site video so you folks can look through it and tailor your fix.
[source.zip](https://github.com/samuraiexx/roll_together/files/6190957/source.zip)

**Comment by JeromySt** [comment]
Just commenting that I have validated 2.9.2 fixes the extension for beta.crunchyroll.com.  Thank you for spending the time to fix this!

**Comment by hsnavarro** [comment]
Thanks for the help providing the information needed to find a solution for your problem.
