### ISSUE TITLE
Create room button gone

### ISSUE THREAD

**Issue by CasperJansson** [samuraiexx/roll_together#18]
I can't get the "create room" button to appear when I play something on Crunchyroll. 

All I get is the menu I get when I'm on anyother website.

What do I do?
![Roll together](https://user-images.githubusercontent.com/86263369/122817713-8f11a800-d2d8-11eb-825a-ddf83f38e8a1.png)

**Comment by samuraiexx** [comment]
Fixed on https://github.com/samuraiexx/roll_together/commit/7ebba767c6e6c8abd5f0f29745e83e94104e5a1a

Thanks for bringing it to our attention.
