### ISSUE TITLE
RollTogether off chrome store

### ISSUE THREAD

**Issue by Griffin17** [samuraiexx/roll_together#33]
It seems that roll together has been taken off the chrome store and when installed links do not work, may be due to crunchyroll website turning off DRM when using an extension for this. Seems other forms of watch parties are affected on crunchyroll too.

**Comment by gibarel1** [comment]
Can confirm, also, cant install it by downloading the repo, error about a missing options file

**Comment by Griffin17** [comment]
All good now back on store and working again
